- name: Write console log to localhost as fact zuul_console_json
  hosts: localhost
  tasks:
    - name: capture console log json as fact
      set_fact:
        zuul_console_json: "{{ lookup('file', zuul.executor.log_root + '/job-output.json') }}"

- name: Collect logs
  hosts: primary
  tasks:
    - name: Copy zuul_console_json log to workspace for reproducer
      copy:
        content: "{{ hostvars['localhost'].zuul_console_json }}"
        dest: "{{ ansible_user_dir }}/workspace/logs/zuul_console.json"

    - name: Run ansible playbook to collect logs
      shell: |
        if [[ -e {{ ansible_user_dir }}/workspace/logs/collect_logs.sh ]]; then
          bash {{ ansible_user_dir }}/workspace/logs/collect_logs.sh
        fi

- hosts:
    - primary
    - centos-7
  tasks:

    - name: Ensure artifacts directory exists
      file:
        path: '{{ zuul.executor.work_root }}/artifacts'
        state: directory
      delegate_to: localhost

    - name: Copy files from {{ ansible_user_dir }}/workspace/ on node
      no_log: true
      failed_when: false
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/logs/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs
